version: '3'
services:
  db:
    container_name: fintess-database
    command: 
      --default-authentication-plugin=caching_sha2_password
      --character-set-server=utf8 
      --collation-server=utf8_general_ci
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitness_club_db
      MYSQL_USER: springroot
      MYSQL_PASSWORD: spring
    ports:
      - 3307:3306
    
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - fitness-net
  app:
    container_name: fintess-app
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fitness_club_db
      SPRING_DATASOURCE_USERNAME: springroot
      SPRING_DATASOURCE_PASSWORD: spring
    ports:
      - 8080:8080
    networks:
      - fitness-net

volumes:
  db-data:

networks:
  fitness-net: 