-- MySQL Script generated by MySQL Workbench
-- Sat Sep 23 22:46:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`membership_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`membership_role` (
  `id_role` INT NOT NULL,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clubs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clubs` (
  `id_club` INT NOT NULL AUTO_INCREMENT,
  `adress` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_club`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`members` (
  `id_member` INT NOT NULL AUTO_INCREMENT,
  `id_role` INT NOT NULL,
  `id_club` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `second_name` VARCHAR(45) NOT NULL,
  `phone_number` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `start_trial_date` DATE NOT NULL,
  `end_trial_date` DATE NULL,
  `gender` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_member`),
  INDEX `fk_members_Roles1_idx` (`id_role` ASC) VISIBLE,
  INDEX `fk_members_clubs1_idx` (`id_club` ASC) VISIBLE,
  CONSTRAINT `fk_members_Roles1`
    FOREIGN KEY (`id_role`)
    REFERENCES `mydb`.`membership_role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_members_clubs1`
    FOREIGN KEY (`id_club`)
    REFERENCES `mydb`.`clubs` (`id_club`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`position` (
  `id_position` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_position`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`staff` (
  `id_staff` INT NOT NULL AUTO_INCREMENT,
  `id_position` INT NOT NULL,
  `id_club` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `second_name` VARCHAR(45) NOT NULL,
  `phone_number` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `hire_date` DATE NOT NULL,
  `staff_about` VARCHAR(100) NULL,
  `gender` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_staff`),
  INDEX `fk_staff_Position1_idx` (`id_position` ASC) VISIBLE,
  INDEX `fk_staff_clubs1_idx` (`id_club` ASC) VISIBLE,
  CONSTRAINT `fk_staff_Position1`
    FOREIGN KEY (`id_position`)
    REFERENCES `mydb`.`position` (`id_position`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_staff_clubs1`
    FOREIGN KEY (`id_club`)
    REFERENCES `mydb`.`clubs` (`id_club`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipment_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipment_type` (
  `id_equipment_type` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_equipment_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipment` (
  `id_equipment` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `quantity` INT NULL,
  `id_equipment_type` INT NOT NULL,
  PRIMARY KEY (`id_equipment`),
  INDEX `fk_equipment_equipment_type1_idx` (`id_equipment_type` ASC) VISIBLE,
  CONSTRAINT `fk_equipment_equipment_type1`
    FOREIGN KEY (`id_equipment_type`)
    REFERENCES `mydb`.`equipment_type` (`id_equipment_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trainers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trainers` (
  `id_staff` INT NOT NULL,
  `id_club` INT NOT NULL,
  `specialty` VARCHAR(45) NULL,
  `experience` DATE NULL,
  `certifications` INT NULL,
  PRIMARY KEY (`id_staff`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gyms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gyms` (
  `id_gym` INT NOT NULL AUTO_INCREMENT,
  `id_club` INT NOT NULL,
  `amount_of_equipment` INT NULL,
  PRIMARY KEY (`id_gym`),
  INDEX `fk_gyms_clubs1_idx` (`id_club` ASC) VISIBLE,
  CONSTRAINT `fk_gyms_clubs1`
    FOREIGN KEY (`id_club`)
    REFERENCES `mydb`.`clubs` (`id_club`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipment_statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipment_statistics` (
  `id_statistics` INT NOT NULL,
  `approaches` INT NULL,
  `kilocalories` INT NULL,
  `activity_type` INT NULL,
  PRIMARY KEY (`id_statistics`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inbody_analyses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inbody_analyses` (
  `id_inbody_analys` INT NOT NULL,
  `height` FLOAT NULL,
  `weight` FLOAT NULL,
  `bmi` FLOAT NULL,
  `fat_percent` FLOAT NULL,
  `muscle_persent` FLOAT NULL,
  PRIMARY KEY (`id_inbody_analys`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`training_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`training_type` (
  `id_training_type` INT NOT NULL AUTO_INCREMENT,
  `training_type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_training_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`training_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`training_schedule` (
  `id_session` INT NOT NULL AUTO_INCREMENT,
  `id_club` INT NOT NULL,
  `id_trainer` INT NULL,
  `id_training_type` INT NOT NULL,
  `workout_description` VARCHAR(45) NULL,
  `session_date` DATE NOT NULL,
  `session_time` INT(90) NOT NULL,
  `training_type` SMALLINT(2) NULL,
  PRIMARY KEY (`id_session`),
  INDEX `fk_personal_training_sessions_trainers1_idx` (`id_trainer` ASC) VISIBLE,
  INDEX `fk_training_schedule_training_type1_idx` (`id_training_type` ASC) VISIBLE,
  INDEX `fk_training_schedule_clubs1_idx` (`id_club` ASC) VISIBLE,
  CONSTRAINT `fk_personal_training_sessions_trainers1`
    FOREIGN KEY (`id_trainer`)
    REFERENCES `mydb`.`trainers` (`id_staff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_training_schedule_training_type1`
    FOREIGN KEY (`id_training_type`)
    REFERENCES `mydb`.`training_type` (`id_training_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_training_schedule_clubs1`
    FOREIGN KEY (`id_club`)
    REFERENCES `mydb`.`clubs` (`id_club`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`account_role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_photo` (
  `id_photo` INT NOT NULL AUTO_INCREMENT,
  `image` BLOB NULL,
  PRIMARY KEY (`id_photo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`accounts` (
  `id_account` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `id_photo` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `account_creation_date` DATE NOT NULL,
  `last_login` DATE NOT NULL,
  PRIMARY KEY (`id_account`),
  INDEX `fk_accounts_account_role1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_accounts_users_photo1_idx` (`id_photo` ASC) VISIBLE,
  CONSTRAINT `fk_accounts_account_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`account_role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accounts_users_photo1`
    FOREIGN KEY (`id_photo`)
    REFERENCES `mydb`.`users_photo` (`id_photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`feedback` (
  `feedback_id` INT NOT NULL AUTO_INCREMENT,
  `id_account` INT NOT NULL,
  `feedback_text` VARCHAR(45) NULL,
  `feedback_date` DATE NULL,
  `rating` INT(10) NULL,
  `feedbackcol` VARCHAR(45) NULL,
  PRIMARY KEY (`feedback_id`, `id_account`),
  INDEX `fk_feedback_accounts1_idx` (`id_account` ASC) VISIBLE,
  CONSTRAINT `fk_feedback_accounts1`
    FOREIGN KEY (`id_account`)
    REFERENCES `mydb`.`accounts` (`id_account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`feedback_has_group_session_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`feedback_has_group_session_schedule` (
  `feedback_id` INT NOT NULL,
  `training_schedule_id_session` INT NOT NULL,
  PRIMARY KEY (`feedback_id`, `training_schedule_id_session`),
  INDEX `fk_feedback_has_group_session_schedule_feedback1_idx` (`feedback_id` ASC) VISIBLE,
  INDEX `fk_feedback_has_group_session_schedule_training_schedule1_idx` (`training_schedule_id_session` ASC) VISIBLE,
  CONSTRAINT `fk_feedback_has_group_session_schedule_feedback1`
    FOREIGN KEY (`feedback_id`)
    REFERENCES `mydb`.`feedback` (`feedback_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feedback_has_group_session_schedule_training_schedule1`
    FOREIGN KEY (`training_schedule_id_session`)
    REFERENCES `mydb`.`training_schedule` (`id_session`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`members_has_equipment_statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`members_has_equipment_statistics` (
  `members_id_member` INT NOT NULL,
  `id_statistics` INT NOT NULL,
  PRIMARY KEY (`members_id_member`, `id_statistics`),
  INDEX `fk_members_has_equipment_statistics_equipment_statistics1_idx` (`id_statistics` ASC) VISIBLE,
  INDEX `fk_members_has_equipment_statistics_members1_idx` (`members_id_member` ASC) VISIBLE,
  CONSTRAINT `fk_members_has_equipment_statistics_members1`
    FOREIGN KEY (`members_id_member`)
    REFERENCES `mydb`.`members` (`id_member`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_members_has_equipment_statistics_equipment_statistics1`
    FOREIGN KEY (`id_statistics`)
    REFERENCES `mydb`.`equipment_statistics` (`id_statistics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`members_has_inbody_analyses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`members_has_inbody_analyses` (
  `members_id_member` INT NOT NULL,
  `id_inbody_analys` INT NOT NULL,
  PRIMARY KEY (`members_id_member`, `id_inbody_analys`),
  INDEX `fk_members_has_inbody_analyses_inbody_analyses1_idx` (`id_inbody_analys` ASC) VISIBLE,
  INDEX `fk_members_has_inbody_analyses_members1_idx` (`members_id_member` ASC) VISIBLE,
  CONSTRAINT `fk_members_has_inbody_analyses_members1`
    FOREIGN KEY (`members_id_member`)
    REFERENCES `mydb`.`members` (`id_member`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_members_has_inbody_analyses_inbody_analyses1`
    FOREIGN KEY (`id_inbody_analys`)
    REFERENCES `mydb`.`inbody_analyses` (`id_inbody_analys`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nutrition_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nutrition_plan` (
  `plan_id` INT NOT NULL AUTO_INCREMENT,
  `id_member` INT NOT NULL,
  `nutrition_description` VARCHAR(100) NULL,
  `start_date` DATE NULL,
  PRIMARY KEY (`plan_id`),
  INDEX `fk_nutrition_plan_members1_idx` (`id_member` ASC) VISIBLE,
  CONSTRAINT `fk_nutrition_plan_members1`
    FOREIGN KEY (`id_member`)
    REFERENCES `mydb`.`members` (`id_member`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`achivements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`achivements` (
  `id_achivement` INT NOT NULL AUTO_INCREMENT,
  `achivement_description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_achivement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`members_has_achivements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`members_has_achivements` (
  `id_member` INT NOT NULL,
  `id_achivement` INT NOT NULL,
  `receipt_date` DATE NOT NULL,
  PRIMARY KEY (`id_member`, `id_achivement`),
  INDEX `fk_members_has_achivements_achivements1_idx` (`id_achivement` ASC) VISIBLE,
  INDEX `fk_members_has_achivements_members1_idx` (`id_member` ASC) VISIBLE,
  CONSTRAINT `fk_members_has_achivements_members1`
    FOREIGN KEY (`id_member`)
    REFERENCES `mydb`.`members` (`id_member`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_members_has_achivements_achivements1`
    FOREIGN KEY (`id_achivement`)
    REFERENCES `mydb`.`achivements` (`id_achivement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`news` (
  `id_news` INT NOT NULL,
  `news_title` VARCHAR(45) NOT NULL,
  `news_text` VARCHAR(200) NULL,
  PRIMARY KEY (`id_news`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`visits_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`visits_history` (
  `id_visit` INT NOT NULL AUTO_INCREMENT,
  `visit_date` DATE NOT NULL,
  PRIMARY KEY (`id_visit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`members_have_visits_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`members_have_visits_history` (
  `id_visit` INT NOT NULL,
  `id_member` INT NOT NULL,
  PRIMARY KEY (`id_visit`, `id_member`),
  INDEX `fk_visits_history_has_members_members1_idx` (`id_member` ASC) VISIBLE,
  INDEX `fk_visits_history_has_members_visits_history1_idx` (`id_visit` ASC) VISIBLE,
  CONSTRAINT `fk_visits_history_has_members_visits_history1`
    FOREIGN KEY (`id_visit`)
    REFERENCES `mydb`.`visits_history` (`id_visit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visits_history_has_members_members1`
    FOREIGN KEY (`id_member`)
    REFERENCES `mydb`.`members` (`id_member`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipment_has_gyms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipment_has_gyms` (
  `equipment_id_equipment` INT NOT NULL,
  `gyms_id_gym` INT NOT NULL,
  PRIMARY KEY (`equipment_id_equipment`, `gyms_id_gym`),
  INDEX `fk_equipment_has_gyms_gyms1_idx` (`gyms_id_gym` ASC) VISIBLE,
  INDEX `fk_equipment_has_gyms_equipment1_idx` (`equipment_id_equipment` ASC) VISIBLE,
  CONSTRAINT `fk_equipment_has_gyms_equipment1`
    FOREIGN KEY (`equipment_id_equipment`)
    REFERENCES `mydb`.`equipment` (`id_equipment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipment_has_gyms_gyms1`
    FOREIGN KEY (`gyms_id_gym`)
    REFERENCES `mydb`.`gyms` (`id_gym`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clubs_has_news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clubs_has_news` (
  `clubs_id_club` INT NOT NULL,
  `news_id_news` INT NOT NULL,
  PRIMARY KEY (`clubs_id_club`, `news_id_news`),
  INDEX `fk_clubs_has_news_news1_idx` (`news_id_news` ASC) VISIBLE,
  INDEX `fk_clubs_has_news_clubs1_idx` (`clubs_id_club` ASC) VISIBLE,
  CONSTRAINT `fk_clubs_has_news_clubs1`
    FOREIGN KEY (`clubs_id_club`)
    REFERENCES `mydb`.`clubs` (`id_club`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clubs_has_news_news1`
    FOREIGN KEY (`news_id_news`)
    REFERENCES `mydb`.`news` (`id_news`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`members_has_training_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`members_has_training_schedule` (
  `id_member` INT NOT NULL,
  `id_session` INT NOT NULL,
  PRIMARY KEY (`id_member`, `id_session`),
  INDEX `fk_members_has_training_schedule_training_schedule1_idx` (`id_session` ASC) VISIBLE,
  INDEX `fk_members_has_training_schedule_members1_idx` (`id_member` ASC) VISIBLE,
  CONSTRAINT `fk_members_has_training_schedule_members1`
    FOREIGN KEY (`id_member`)
    REFERENCES `mydb`.`members` (`id_member`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_members_has_training_schedule_training_schedule1`
    FOREIGN KEY (`id_session`)
    REFERENCES `mydb`.`training_schedule` (`id_session`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
