-- MySQL Script generated by MySQL Workbench
-- Thu Sep 14 12:27:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clubs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clubs` (
  `id_club` INT NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_club`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`membership_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`membership_role` (
  `id_role` INT NOT NULL,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`members` (
  `id_member` INT NOT NULL,
  `id_club` INT NOT NULL,
  `id_role` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `second_name` VARCHAR(45) NOT NULL,
  `phone_number` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `start_trial_date` DATE NOT NULL,
  `end_trial_date` DATE NULL,
  PRIMARY KEY (`id_member`),
  INDEX `fk_members_clubs1_idx` (`id_club` ASC) VISIBLE,
  INDEX `fk_members_Roles1_idx` (`id_role` ASC) VISIBLE,
  CONSTRAINT `fk_members_clubs1`
    FOREIGN KEY (`id_club`)
    REFERENCES `mydb`.`clubs` (`id_club`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_members_Roles1`
    FOREIGN KEY (`id_role`)
    REFERENCES `mydb`.`membership_role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`position` (
  `id_position` INT NOT NULL,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_position`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`staff` (
  `id_staff` INT NOT NULL,
  `id_club` INT NOT NULL,
  `id_position` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `second_name` VARCHAR(45) NULL,
  `phone_number` INT NULL,
  `email` VARCHAR(45) NULL,
  `hire_date` DATE NULL,
  PRIMARY KEY (`id_staff`),
  INDEX `fk_staff_clubs1_idx` (`id_club` ASC) VISIBLE,
  INDEX `fk_staff_Position1_idx` (`id_position` ASC) VISIBLE,
  CONSTRAINT `fk_staff_clubs1`
    FOREIGN KEY (`id_club`)
    REFERENCES `mydb`.`clubs` (`id_club`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_staff_Position1`
    FOREIGN KEY (`id_position`)
    REFERENCES `mydb`.`position` (`id_position`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipment` (
  `id_equipment` INT NOT NULL,
  `id_club` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `ID_type` VARCHAR(45) NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`id_equipment`),
  INDEX `fk_equipment_clubs1_idx` (`id_club` ASC) VISIBLE,
  CONSTRAINT `fk_equipment_clubs1`
    FOREIGN KEY (`id_club`)
    REFERENCES `mydb`.`clubs` (`id_club`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trainers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trainers` (
  `id_trainer` INT NOT NULL,
  `id_club` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `second_name` VARCHAR(45) NULL,
  `specialty` VARCHAR(45) NULL,
  `experience` DATE NULL,
  `certifications` INT NULL,
  PRIMARY KEY (`id_trainer`),
  INDEX `fk_Trainers_clubs1_idx` (`id_club` ASC) VISIBLE,
  CONSTRAINT `fk_Trainers_clubs1`
    FOREIGN KEY (`id_club`)
    REFERENCES `mydb`.`clubs` (`id_club`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`class_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`class_schedule` (
  `id_class_schedule` INT NOT NULL,
  `id_trainer` INT NOT NULL,
  `id_class` VARCHAR(45) NULL,
  PRIMARY KEY (`id_class_schedule`),
  INDEX `fk_Class_schedule_Trainers_idx` (`id_trainer` ASC) VISIBLE,
  CONSTRAINT `fk_Class_schedule_Trainers`
    FOREIGN KEY (`id_trainer`)
    REFERENCES `mydb`.`trainers` (`id_trainer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`invoices` (
  `id_invoice` INT NOT NULL,
  `id_member` INT NOT NULL,
  `date` DATE NOT NULL,
  `total_amount` INT NOT NULL,
  `payment_status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_invoice`),
  INDEX `fk_invoices_members1_idx` (`id_member` ASC) VISIBLE,
  CONSTRAINT `fk_invoices_members1`
    FOREIGN KEY (`id_member`)
    REFERENCES `mydb`.`members` (`id_member`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`locker_rental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`locker_rental` (
  `id_locker` INT NOT NULL,
  `id_member` INT NOT NULL,
  `locker_number` INT NULL,
  `rental_start_date` DATE NULL,
  PRIMARY KEY (`id_locker`),
  INDEX `fk_locker_rental_members1_idx` (`id_member` ASC) VISIBLE,
  CONSTRAINT `fk_locker_rental_members1`
    FOREIGN KEY (`id_member`)
    REFERENCES `mydb`.`members` (`id_member`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
